tree_game_optimistic_nash_v:
    iterations: 5000
    eval_interval: 20
    num_games: 10
    num_runs: 1
    # ==== Game ====
    game: tree_game
    game_config:
        bias: 0.5
        depth:
            grid_search: [4, 5, 6]
        actions: 
            grid_search: [4, 5, 6]
    # ==== Algorithm ====
    alg: optimistic_nash_v
    alg_config: 
        iteration_episodes: 10
        gamma: 0.1
        beta: 0.0
        eta: 10.0
        averaging:
            grid_search: [False, True]