multi_matrix_2contextual_eval:
  run: DEEP_NASH_V2
  stop:
    timesteps_total: 1000000
  checkpoint_at_end: true
  checkpoint_freq: 100
  num_samples: 2
  config:
    in_evaluation: true
    evaluation_interval: 1
    # === Environment ===
    env: multi_matrix
    env_config:
      num_contexts: 4
    # === Curiosity ===
    model:
      custom_options:
        weight: 0.5
        decay: 0.2
        burn_in: 1600
        delay: 800
        curiosity_module: RND
        curiosity_config:
          fcnet_activation: relu
          fcnet_hiddens: [ 256, 256 ]
          fcnet_outputs: 32
          agent_action: True
          joint_action: False
    # === Intrinsic PPO ===
    intrinsic_gamma: 0.95
    intrinsic_lambda: 0.95
    num_agents: 2
    # === PPO ===
    lambda: 0.95
    gamma: 0.99
    entropy_coeff: 0.001
    clip_param: 0.1
    lr: 0.000001
    num_sgd_iter: 8
    sgd_minibatch_size: 32
    train_batch_size: 160
    rollout_fragment_length: 40
    batch_mode: complete_episodes
    average_buffer_size: 10000
    average_minibatch_size: 32
