rnd_cyclic_contextual:
    run: PPO_CURIOSITY
    stop:
        timesteps_total: 100000
    checkpoint_at_end: True
    checkpoint_freq: 200
    num_samples: 2
    config:
        evaluation_interval: 1
        # === Environment ===
        env: roshambo
        env_config:
            transitive_actions: 0
            cyclic_actions: 3
            num_contexts: 3
            eval_steps: 100
        # === PPO ===
        lambda: 0.95
        gamma: 0.99
        entropy_coeff: 0.001
        clip_param: 0.1
        lr: 0.000001
        num_sgd_iter: 8
        sgd_minibatch_size: 32
        train_batch_size: 160
        rollout_fragment_length: 40
        batch_mode: complete_episodes
        num_gpus: 1