simultaneous_tree_game_optimistic_nash_q:
    iterations: 5000
    eval_interval: 10
    num_games: 10
    num_runs: 1
    # ==== Game ====
    game: simultaneous_tree_game
    game_config:
        bias: 
            grid_search: [0.5, 0.1]
        depth:
            grid_search: [3, 4, 5]
        actions: 3
    # ==== Algorithm ====
    alg: nash_q
    alg_config: 
        iteration_episodes: 1
        initial_value:
            grid_search: [0.0, 1.0]
        epsilon:
            grid_search: [0.0, 0.1]