kuhn_poker_rnd:
    run: SIMULTANEOUS_PLAY
    stop:
        timesteps_total: 500000
    checkpoint_freq: 500
    checkpoint_at_end: True
    num_samples: 5
    config:
        alg: PPO_CURIOSITY
        # === Evaluation ===
        population:
          - path: populations/kuhn_poker_ppo
            alg: SIMULTANEOUS_PLAY
            mapping: [[1, learned_policy_1]]
        random_eval: True
        multiagent_eval_interval: 20
        # === Environment ===
        horizon: 500
        env: openspiel
        env_config:
            game: kuhn_poker
        # === Curiosity ===
        model:
            custom_options:
                start_weight: 1.0
                end_weight: 0.0
                exploration_steps: 80000
                burn_in: 8000
                delay: 4000
                decay: 0.02
                curiosity_module: RND
                curiosity_config:
                    scale: 0.5
                    fcnet_activation: elu
                    fcnet_hiddens: [256, 256]
                    fcnet_outputs: 32
                    agent_action: True
                    joint_action: False
        # === Curiosity PPO ===
        intrinsic_lambda: 0.95
        intrinsic_gamma: 0.95
        num_agents: 2
        # === PPO ===
        lambda: 0.95
        gamma: 0.95
        entropy_coeff: 0.001
        clip_param: 0.1
        lr: 0.001
        num_sgd_iter: 8
        train_batch_size: 400
        rollout_fragment_length: 100
        batch_mode: truncate_episodes