alpha_beta_optimistic_nash_q_tune:
    iterations: 500
    eval_interval: 1
    num_games: 4
    num_runs: 1
    # ==== Game ====
    game: alpha_beta
    game_config:
        bias: 0.5
        depth:
            grid_search: [4, 5, 6]
        actions: 
            grid_search: [4, 5, 6]
    # ==== Algorithm ====
    alg: optimistic_nash_q
    alg_config: 
        iteration_episodes: 100
        beta: 0.0
        exploit:
            grid_search: [False, True]
        averaging:
            grid_search: [False, True]