venture_rnd:
    run: PPO_CURIOSITY
    stop:
        timesteps_total: 6000000
    checkpoint_at_end: True
    num_samples: 4
    config:
        # === Environment ===
        env: gym_atari
        env_config:
            game: Venture-v4
        # === Curiosity ===
        model:
            custom_options: 
                weight: 0.5
                decay: 0.2
                burn_in: 1600
                delay: 800
                curiosity_module: RND
                curiosity_config:
                    fcnet_activation: relu
                    fcnet_hiddens: [256, 256]
                    fcnet_outputs: 32
                    agent_action: True
                    joint_action: False
        # === Intrinsic PPO ===
        intrinsic_gamma: 0.95
        intrinsic_lambda: 0.95
        num_agents: 1
        # === PPO ===
        lambda: 0.95
        gamma: 0.99
        kl_coeff: 0.0
        entropy_coeff: 0.01
        clip_rewards: True
        clip_param: 0.1
        lr: 0.00001
        num_sgd_iter: 8
        sgd_minibatch_size: 512
        train_batch_size: 1600
        rollout_fragment_length: 100
        num_envs_per_worker: 4
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        vf_share_layers: true
        num_gpus: 1