alpha_beta_optimistic_q_learning:
    iterations: 5000
    eval_interval: 20
    num_games: 10
    num_runs: 1
    # ==== Game ====
    game: alpha_beta
    game_config:
        bias: 0.5
        depth:
            grid_search: [4, 5, 6]
        actions: 
            grid_search: [4, 5, 6]
    # ==== Algorithm ====
    alg: optimistic_q_learning
    alg_config: 
        iteration_episodes: 10
        gamma: 1.0
        epsilon: 0.05
        exploit: True
        beta: 0.0
        averaging:
            grid_search: [False, True]