deep_sea_optimistic_nash_v_tune:
    iterations: 500
    eval_interval: 1
    num_games: 5
    num_runs: 1
    # ==== Game ====
    game: deep_sea
    game_config:
        size:
            grid_search: [10, 20, 40]
        penalty: 
            grid_search: [0.0, 0.01]
    # ==== Algorithm ====
    alg: optimistic_nash_v
    alg_config: 
        iteration_episodes: 100
        eta: 
            grid_search: [10.0, 100.0]
        gamma:
            grid_search: [0.1, 0.5, 1.0]
        beta:
            grid_search: [0.0, 1.0, 10.0]